<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>nh</string>
	</array>
	<key>name</key>
	<string>Note Hashtag</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Line Comments</string>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.line.double-slash.nh</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Strings</string>
			<key>match</key>
			<string>\"((\\\")|[^\"])*\"</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Language literals</string>
			<key>match</key>
			<string>\b(true|false|~)\b</string>
			<key>name</key>
			<string>constant.language.nh</string>
		</dict>
		<dict>
			<key>match</key>
			<string>({|}|\[|\]|\(|\))</string>
			<key>name</key>
			<string>support.constant.nh</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([-+]?\d*\.?\d+)(e(\+?|-)\d+)?</string>
			<key>name</key>
			<string>constant.numeric.nh</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Built in types</string>
			<key>match</key>
			<string>\b(int|string|float|unit|bool|fun|type)\b</string>
			<key>name</key>
			<string>storage.type.nh</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(pitch|chord|track|song)\b</string>
			<key>name</key>
			<string>storage.type.nh</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Modifiers</string>
			<key>match</key>
			<string>(const)</string>
			<key>name</key>
			<string>storage.modifier.nh</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Operator keywords</string>
			<key>match</key>
			<string>\b(init|beget|bringintobeing|-&gt;)\b</string>
			<key>name</key>
			<string>keyword.operator.other.nh</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Conditional Control Keywords</string>
			<key>match</key>
			<string>\b(if|then|else|be|unless|inwhichcase)\b</string>
			<key>name</key>
			<string>keyword.control.conditional.nh</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Loop Control Keywords</string>
			<key>match</key>
			<string>\b(for|in|do)\b</string>
			<key>name</key>
			<string>keyword.control.loop.nh</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Other control keywords</string>
			<key>match</key>
			<string>\b(include|extern|throw)\b</string>
			<key>name</key>
			<string>keyword.control.other.nh</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\|\||\&amp;\&amp;|==|!=|!|&lt;=|&gt;=|&gt;|&lt;)</string>
			<key>name</key>
			<string>keyword.operator.bool.nh</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(|\+|\-|\*|/|%)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.nh</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Variables</string>
			<key>match</key>
			<string>\b[a-z_][A-Za-z0-9_]*\b</string>
			<key>name</key>
			<string>variable.other.nh</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Functions</string>
			<key>match</key>
			<string>\b[A-Z][A-Za-z0-9_]*\b</string>
			<key>name</key>
			<string>variable.other.nh</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(#|:|@|b|,)</string>
			<key>name</key>
			<string>keyword.operator.musical.nh</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\.)\b|(=|,|\$)</string>
			<key>name</key>
			<string>keyword.operator.other.nh</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.nh</string>
	<key>uuid</key>
	<string>7f6b19e8-b940-426b-b77b-a2593befdc39</string>
</dict>
</plist>
